// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdfwqnenqpoygnoqsstb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZndxbmVucXBveWdub3Fzc3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTE5MjIsImV4cCI6MjA3MDMyNzkyMn0.9Um0CP9_ylf1GEwo4Pf4_sqaxgU0x_nRulBFLY14-GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});